create table lottery (id int8 generated by default as identity, moment timestamp, numbers varchar(255), user_id int8, primary key (id));
create table users (id int8 generated by default as identity, email varchar(255), primary key (id));
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table if exists lottery add constraint FKgtobsk8i1nri03dsp51wk8xc1 foreign key (user_id) references users;
